from __future__ import annotations

import time
from datetime import datetime, timezone
from pathlib import Path

from fastapi import Depends, FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

from .config import Settings, get_settings
from .copilot import explain
from .demo_models import ensure_demo_models
from .engines import LocalGeometryAnalysisEngine
from .exporters import viewer_arrays, write_issues_csv, write_run_json
from .geometry import compute_metrics
from .inspections import run_inspections
from .models import CopilotRequest, CopilotResponse, InspectionRun, ProcessingStage, RepairRequest, RepairResult, ViewerPayload
from .parsers import ParseError
from .repair_engine import GeometryRepairEngine
from .repairs import SAFE_REPAIRS, apply_repairs
from .reports import write_pdf_report
from .scoring import calculate_scores
from .storage import Store

app = FastAPI(title="MODOC API", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://birdwalk.github.io",
    ],
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


settings = get_settings()
store = Store(settings)
engine = LocalGeometryAnalysisEngine()
repair_engine = GeometryRepairEngine()
DEMO_MODELS = module_path = Path(__file__).resolve()
project_root = module_path.parents[3] if len(module_path.parents) > 3 else Path.cwd()
DEMO_MODELS = ensure_demo_models(project_root)


def get_store() -> Store:
    return store


@app.get("/")
def root() -> dict[str, str]:
    return {"service": "MODOC API", "docs": "/docs", "health": "/api/v1/health"}


@app.get("/api/v1/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "MODOC"}


@app.get("/api/v1/projects")
def list_projects() -> list[dict[str, str]]:
    return [{"id": "local-demo-project", "name": "Local Inspection Project"}]


@app.post("/api/v1/projects")
def create_project() -> dict[str, str]:
    return {"id": "local-demo-project", "name": "Local Inspection Project"}


@app.get("/api/v1/demo-models")
def demo_models() -> list[dict[str, str]]:
    return [{"id": key, "name": key.replace("-", " ").title(), "format": path.suffix.upper().lstrip("."), "provenance": "Programmatically generated by MODOC"} for key, path in DEMO_MODELS.items()]


@app.post("/api/v1/demo-models/{demo_id}/load")
def load_demo(demo_id: str, intended_use: str = "3d_printing", db: Store = Depends(get_store)) -> InspectionRun:
    if demo_id not in DEMO_MODELS:
        raise HTTPException(status_code=404, detail="Demo model not found.")
    model_id, path, checksum, duplicate = db.register_demo(DEMO_MODELS[demo_id])
    return _create_run(db, model_id, path, checksum, duplicate, intended_use)


@app.post("/api/v1/projects/{project_id}/models")
def create_model(project_id: str) -> dict[str, str]:
    return {"id": store.new_id("model"), "project_id": project_id}


@app.post("/api/v1/models/upload")
async def upload_model(file: UploadFile = File(...), intended_use: str = "general", db: Store = Depends(get_store)) -> InspectionRun:
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in {".stl", ".obj", ".glb", ".gltf"}:
        raise HTTPException(status_code=415, detail="Unsupported format. Export to STL, OBJ or GLB for this MVP.")
    try:
        model_id, path, checksum, duplicate = await db.save_upload(file)
    except ValueError as exc:
        raise HTTPException(status_code=413, detail=str(exc)) from exc
    return _create_run(db, model_id, path, checksum, duplicate, intended_use)


@app.post("/api/v1/models/{model_id}/files")
async def upload_model_file(model_id: str, file: UploadFile = File(...), intended_use: str = "general", db: Store = Depends(get_store)) -> InspectionRun:
    return await upload_model(file=file, intended_use=intended_use, db=db)


@app.post("/api/v1/models/{model_id}/inspection-runs")
def create_inspection_run(model_id: str, intended_use: str = "general", db: Store = Depends(get_store)) -> InspectionRun:
    path = db.files.get(model_id)
    if not path:
        raise HTTPException(status_code=404, detail="Model file not found.")
    checksum = path.read_bytes().hex()[:64]
    return _create_run(db, model_id, path, checksum, False, intended_use)


@app.get("/api/v1/inspection-runs/{run_id}")
def get_run(run_id: str, db: Store = Depends(get_store)) -> InspectionRun:
    run = db.runs.get(run_id)
    if not run:
        raise HTTPException(status_code=404, detail="Inspection run not found.")
    return run


@app.get("/api/v1/inspection-runs/{run_id}/issues")
def get_issues(run_id: str, db: Store = Depends(get_store)):
    return get_run(run_id, db).issues


@app.get("/api/v1/inspection-runs/{run_id}/viewer")
def get_viewer(run_id: str, db: Store = Depends(get_store)) -> ViewerPayload:
    run = get_run(run_id, db)
    mesh = db.meshes[run.version_id]
    vertices, indices, vertex_colors = viewer_arrays(mesh, settings.preview_triangle_limit)
    return ViewerPayload(vertices=vertices, indices=indices, vertex_colors=vertex_colors, issues=run.issues, metrics=run.metrics)


@app.post("/api/v1/inspection-runs/{run_id}/repairs/preview")
def preview_repair(run_id: str, request: RepairRequest, db: Store = Depends(get_store)) -> dict:
    run = get_run(run_id, db)
    mesh = db.meshes[run.version_id]
    if "SAFE_ALL" in request.repair_ids:
        plan = repair_engine.createRepairPlan(run.issues)
        repair_ids = [issue.rule_id for issue in run.issues if any(operation.issue_id == issue.id and operation.auto_fix_eligible for operation in plan.operations)]
    else:
        plan = repair_engine.createRepairPlan([issue for issue in run.issues if issue.rule_id in request.repair_ids])
        repair_ids = request.repair_ids
    repaired, applied, skipped = apply_repairs(mesh, repair_ids)
    metrics = compute_metrics(repaired, f"preview-{run.metrics.filename}", "native-repair-preview", "0.1")
    issues = run_inspections(repaired, run.intended_use)
    return {
        "operations": [operation.__dict__ for operation in plan.operations],
        "applied_repairs": applied,
        "skipped_repairs": skipped,
        "before": run.metrics,
        "after_metrics": metrics,
        "remaining_issues": issues,
        "geometry_will_change": metrics.geometry_hash != run.metrics.geometry_hash,
        "score_before": run.health_scores.selected_use_score,
        "score_after_estimate": calculate_scores(issues, run.intended_use).selected_use_score,
    }


@app.post("/api/v1/inspection-runs/{run_id}/repairs/apply")
def apply_repair(run_id: str, request: RepairRequest, db: Store = Depends(get_store)) -> RepairResult:
    source_run = get_run(run_id, db)
    mesh = db.meshes[source_run.version_id]
    if source_run.metrics.face_count > settings.max_repair_triangles:
        raise HTTPException(status_code=422, detail="Model exceeds configured repair triangle limit.")
    artifact_id, artifact_path = db.artifact_path(f"{source_run.metrics.filename.rsplit('.', 1)[0]}-modoc-repaired.obj")
    if "SAFE_ALL" in request.repair_ids:
        engine_result = repair_engine.applySafeRepairs(mesh, source_run.issues, source_run.intended_use, artifact_path)
    else:
        engine_result = repair_engine.applySelectedRepairs(mesh, request.repair_ids, source_run.intended_use, artifact_path)
    if not engine_result.validation.valid:
        raise HTTPException(status_code=422, detail=engine_result.validation.message)
    repaired = engine_result.repaired_mesh
    applied = engine_result.applied_repairs
    skipped = engine_result.skipped_repairs + engine_result.failed_repairs
    version_id = db.new_id("version")
    db.meshes[version_id] = repaired
    db.register_artifact(artifact_id, artifact_path, "repaired_model", "model/obj")
    after_run = _create_run_from_mesh(db, source_run.model_id, version_id, repaired, artifact_path.name, source_run.intended_use, ["Repair applied: " + ", ".join(applied), "Exported repaired OBJ and revalidated parser output."])
    result = RepairResult(
        id=db.new_id("repair"),
        source_run_id=run_id,
        version_id=version_id,
        applied_repairs=applied,
        skipped_repairs=skipped,
        before_metrics=source_run.metrics,
        before_health_score=source_run.health_scores.selected_use_score,
        after_health_score=after_run.health_scores.selected_use_score,
        after_run=after_run,
        artifact_id=artifact_id,
        audit_trail=[f"{_now()} Copied source version before repair.", f"{_now()} Applied repairs: {', '.join(applied) or 'none'}."],
    )
    db.repairs[result.id] = result
    return result


@app.post("/api/v1/inspection-runs/{run_id}/copilot")
def copilot(run_id: str, request: CopilotRequest, db: Store = Depends(get_store)) -> CopilotResponse:
    return explain(get_run(run_id, db), request)


@app.post("/api/v1/inspection-runs/{run_id}/reports")
def create_report(run_id: str, db: Store = Depends(get_store)) -> dict[str, str]:
    run = get_run(run_id, db)
    pdf_id, pdf_path = db.artifact_path(f"{run.metrics.filename.rsplit('.', 1)[0]}-geometry-report.pdf")
    json_id, json_path = db.artifact_path(f"{run.metrics.filename.rsplit('.', 1)[0]}-inspection.json")
    csv_id, csv_path = db.artifact_path(f"{run.metrics.filename.rsplit('.', 1)[0]}-issues.csv")
    write_pdf_report(pdf_path, run, explain(run))
    write_run_json(run, json_path)
    write_issues_csv(run.issues, csv_path)
    db.register_artifact(pdf_id, pdf_path, "pdf_report", "application/pdf")
    db.register_artifact(json_id, json_path, "inspection_json", "application/json")
    db.register_artifact(csv_id, csv_path, "issues_csv", "text/csv")
    return {"pdf": pdf_id, "json": json_id, "csv": csv_id}


@app.get("/api/v1/artifacts/{artifact_id}/download")
def download_artifact(artifact_id: str, db: Store = Depends(get_store)) -> FileResponse:
    artifact = db.artifact_index.get(artifact_id)
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found.")
    path = Path(artifact.path).resolve()
    if not str(path).startswith(str(db.root)):
        raise HTTPException(status_code=403, detail="Artifact path rejected.")
    return FileResponse(path, media_type=artifact.content_type, filename=artifact.filename)


@app.get("/api/v1/repair-options")
def repair_options() -> dict[str, str]:
    return SAFE_REPAIRS


def _create_run(db: Store, model_id: str, path: Path, checksum: str, duplicate: bool, intended_use: str) -> InspectionRun:
    try:
        parsed = engine.parse(path)
    except ParseError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    mesh, parser, parser_version = parsed.mesh, parsed.parser, parsed.parser_version
    if len(mesh.faces) > settings.max_triangles:
        raise HTTPException(status_code=422, detail=f"This model has {len(mesh.faces):,} triangles, above the current MODOC analysis limit of {settings.max_triangles:,}. Reduce or decimate the mesh, or raise MODELDOCTOR_MAX_TRIANGLES for a larger workstation demo.")
    version_id = db.new_id("version")
    db.meshes[version_id] = mesh
    return _create_run_from_mesh(db, model_id, version_id, mesh, path.name, intended_use, [f"{_now()} Source checksum {checksum}.", f"{_now()} Duplicate upload detected: {duplicate}."] , parser, parser_version)


def _create_run_from_mesh(db: Store, model_id: str, version_id: str, mesh, filename: str, intended_use: str, audit: list[str], parser: str = "native", parser_version: str = "0.1") -> InspectionRun:
    start = time.perf_counter()
    metrics = compute_metrics(mesh, filename, parser, parser_version)
    issues = run_inspections(mesh, intended_use)
    scores = calculate_scores(issues, intended_use)
    run = InspectionRun(
        id=db.new_id("run"),
        model_id=model_id,
        version_id=version_id,
        intended_use=intended_use,
        status=ProcessingStage.COMPLETED,
        metrics=metrics,
        issues=issues,
        health_scores=scores,
        analysis_duration_ms=round((time.perf_counter() - start) * 1000),
        created_at=_now(),
        audit_trail=audit + [
            f"{_now()} Parsed geometry.",
            f"{_now()} Computed metrics.",
            f"{_now()} Ran deterministic inspections.",
            f"{_now()} Generated viewer payload.",
        ],
    )
    db.runs[run.id] = run
    return run


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()
